"""ci_origem em pull_requests (ADR-0056, MEL-12)

PRs legadas com CI já reportada ficam `desconhecida`: antes desta revisão não havia
como distinguir CI executada de declarada, e afirmar qualquer uma das duas seria
inventar evidência. PRs ainda `pending` ficam com origem vazia (sem CI).

Revision ID: 20755cca5b90
Revises: 96e6315ca1bf
Create Date: 2026-09-15 01:21:18.907881
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20755cca5b90'
down_revision: str | None = '96e6315ca1bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('ci_origem', sa.String(), nullable=False, server_default='')
        )
    op.execute(
        "UPDATE pull_requests SET ci_origem = 'desconhecida' WHERE ci_status <> 'pending'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_column('ci_origem')

    # ### end Alembic commands ###
