"""index orchestrations.created_at

Revision ID: 4e9c3ebf3ad9
Revises: 6178982e6750
Create Date: 2026-07-03 14:02:48.803309
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4e9c3ebf3ad9'
down_revision: str | None = '6178982e6750'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orchestrations_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestrations_created_at'))

    # ### end Alembic commands ###
