"""initial schema

Revision ID: 5023217eb96c
Revises: 
Create Date: 2026-07-03 09:58:29.835875
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '5023217eb96c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('current_phase', sa.String(), nullable=False),
    sa.Column('snapshot_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orchestrations_status'), ['status'], unique=False)

    op.create_table('adr_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adr_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('rel', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adr_links', schema=None) as batch_op:
        batch_op.create_index('ix_adr_links_adr_rel', ['adr_id', 'rel'], unique=False)

    op.create_table('adr_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adr_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pros', sa.JSON(), nullable=False),
    sa.Column('cons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adr_options', schema=None) as batch_op:
        batch_op.create_index('ix_adr_options_adr', ['adr_id'], unique=False)

    op.create_table('adrs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('created_by_agent', sa.String(), nullable=True),
    sa.Column('reviewed_by_agent', sa.String(), nullable=True),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id', 'orchestration_id')
    )
    with op.batch_alter_table('adrs', schema=None) as batch_op:
        batch_op.create_index('ix_adrs_orch_status', ['orchestration_id', 'status'], unique=False)

    op.create_table('boards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('card_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_events_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_events_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('context_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('patch_type', sa.String(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_history_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_orch_seq', ['orchestration_id', 'seq'], unique=False)

    op.create_table('execution_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('fallback_strategy', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_plans_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('human_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('requested_by_agent', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_orch_status', ['orchestration_id', 'status'], unique=False)

    op.create_table('orchestrator_contexts',
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('orchestration_id')
    )
    op.create_table('quality_gate_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_gate_results_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('snapshot_version', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('context_hash', sa.String(), nullable=False),
    sa.Column('quality_gate_result_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_orchestration_id'), ['orchestration_id'], unique=False)

    op.create_table('value_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('rel', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('value_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_value_items_orchestration_id'), ['orchestration_id'], unique=False)
        batch_op.create_index('ix_value_items_owner', ['owner_type', 'owner_id', 'rel'], unique=False)

    op.create_table('board_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_columns_board_id'), ['board_id'], unique=False)

    op.create_table('gate_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['quality_gate_results.id'], ),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gate_criteria', schema=None) as batch_op:
        batch_op.create_index('ix_gate_criteria_gate', ['gate_id'], unique=False)

    op.create_table('kanban_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assignee_type', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('worktree', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.create_index('ix_cards_orch_status', ['orchestration_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_cards_board_id'), ['board_id'], unique=False)

    op.create_table('planned_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('parallel_group', sa.String(), nullable=True),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_agents_plan_id'), ['plan_id'], unique=False)

    op.create_table('card_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('rel', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['kanban_cards.id'], ),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_links', schema=None) as batch_op:
        batch_op.create_index('ix_card_links_card_rel', ['card_id', 'rel'], unique=False)
        batch_op.create_index('ix_card_links_orch_rel_value', ['orchestration_id', 'rel', 'value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_links', schema=None) as batch_op:
        batch_op.drop_index('ix_card_links_orch_rel_value')
        batch_op.drop_index('ix_card_links_card_rel')

    op.drop_table('card_links')
    with op.batch_alter_table('planned_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_agents_plan_id'))

    op.drop_table('planned_agents')
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_cards_board_id'))
        batch_op.drop_index('ix_cards_orch_status')

    op.drop_table('kanban_cards')
    with op.batch_alter_table('gate_criteria', schema=None) as batch_op:
        batch_op.drop_index('ix_gate_criteria_gate')

    op.drop_table('gate_criteria')
    with op.batch_alter_table('board_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_columns_board_id'))

    op.drop_table('board_columns')
    with op.batch_alter_table('value_items', schema=None) as batch_op:
        batch_op.drop_index('ix_value_items_owner')
        batch_op.drop_index(batch_op.f('ix_value_items_orchestration_id'))

    op.drop_table('value_items')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_orchestration_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_orchestration_id'))

    op.drop_table('quality_gate_results')
    op.drop_table('orchestrator_contexts')
    with op.batch_alter_table('human_approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_orch_status')

    op.drop_table('human_approvals')
    with op.batch_alter_table('execution_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_plans_orchestration_id'))

    op.drop_table('execution_plans')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_orch_seq')

    op.drop_table('events')
    with op.batch_alter_table('context_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_history_orchestration_id'))

    op.drop_table('context_history')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_orchestration_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('card_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_events_orchestration_id'))
        batch_op.drop_index(batch_op.f('ix_card_events_card_id'))

    op.drop_table('card_events')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_orchestration_id'))

    op.drop_table('boards')
    with op.batch_alter_table('adrs', schema=None) as batch_op:
        batch_op.drop_index('ix_adrs_orch_status')

    op.drop_table('adrs')
    with op.batch_alter_table('adr_options', schema=None) as batch_op:
        batch_op.drop_index('ix_adr_options_adr')

    op.drop_table('adr_options')
    with op.batch_alter_table('adr_links', schema=None) as batch_op:
        batch_op.drop_index('ix_adr_links_adr_rel')

    op.drop_table('adr_links')
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestrations_status'))

    op.drop_table('orchestrations')
    # ### end Alembic commands ###
