"""catalogo_de_agentes

Revision ID: 54e2ef2b7e2f
Revises: 950ff92ac96e
Create Date: 2026-08-09 22:23:36.502320
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "54e2ef2b7e2f"
down_revision: str | None = "950ff92ac96e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_JSONB = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_definitions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("funcao", sa.Text(), nullable=False),
        sa.Column("plataforma", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("modelos_permitidos", _JSONB, nullable=False),
        sa.Column("efforts_permitidos", _JSONB, nullable=False),
        sa.Column("ferramentas", _JSONB, nullable=False),
        sa.Column("permissoes", _JSONB, nullable=False),
        sa.Column("projetos", _JSONB, nullable=False),
        sa.Column("categorias_tarefa", _JSONB, nullable=False),
        sa.Column("limite_custo_usd", sa.Float(), nullable=True),
        sa.Column("limite_tentativas", sa.Integer(), nullable=True),
        sa.Column("exige_supervisao", sa.Boolean(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_definitions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_definitions_ativo"), ["ativo"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_definitions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_definitions_role"), ["role"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_definitions_role"))
        batch_op.drop_index(batch_op.f("ix_agent_definitions_created_at"))
        batch_op.drop_index(batch_op.f("ix_agent_definitions_ativo"))

    op.drop_table("agent_definitions")
    # ### end Alembic commands ###
