"""context_patches audit table

Revision ID: 6178982e6750
Revises: 5023217eb96c
Create Date: 2026-07-03 10:17:34.851765
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6178982e6750'
down_revision: str | None = '5023217eb96c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_patches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('patch_type', sa.String(), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('linked_adrs', sa.JSON(), nullable=False),
    sa.Column('requires_adr', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_patches', schema=None) as batch_op:
        batch_op.create_index('ix_patches_orch_status', ['orchestration_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('context_patches', schema=None) as batch_op:
        batch_op.drop_index('ix_patches_orch_status')

    op.drop_table('context_patches')
    # ### end Alembic commands ###
