"""slo_evaluations

Revision ID: 7a759f873114
Revises: 9149277d0e97
Create Date: 2026-07-08 20:43:13.141374
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7a759f873114'
down_revision: str | None = '9149277d0e97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slo_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('fail_rate', sa.Float(), nullable=False),
    sa.Column('burn_rate', sa.Float(), nullable=False),
    sa.Column('consumed_pct', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('breaches', sa.JSON(), nullable=False),
    sa.Column('alerts_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slo_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_slo_evals_orch_created', ['orchestration_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slo_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_slo_evals_orch_created')

    op.drop_table('slo_evaluations')
    # ### end Alembic commands ###
