"""candidate_runs

Revision ID: 9149277d0e97
Revises: dc4914a546ae
Create Date: 2026-07-08 19:43:02.425193
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9149277d0e97'
down_revision: str | None = 'dc4914a546ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('recommended_branch', sa.String(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_runs', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_runs_orch_card', ['orchestration_id', 'card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_runs_orch_card')

    op.drop_table('candidate_runs')
    # ### end Alembic commands ###
