"""auditoria_do_card_event

Revision ID: 950ff92ac96e
Revises: f591aac9289f
Create Date: 2026-08-09 15:50:38.383065
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "950ff92ac96e"
down_revision: str | None = "f591aac9289f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("effort", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("phase", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("execution_id", sa.String(), nullable=True))
        batch_op.create_index("ix_card_events_actor", ["actor"], unique=False)
        batch_op.create_index("ix_card_events_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_card_events_execution_id"), ["execution_id"], unique=False
        )
        batch_op.create_index("ix_card_events_phase", ["phase"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card_events", schema=None) as batch_op:
        batch_op.drop_index("ix_card_events_phase")
        batch_op.drop_index(batch_op.f("ix_card_events_execution_id"))
        batch_op.drop_index("ix_card_events_created_at")
        batch_op.drop_index("ix_card_events_actor")
        batch_op.drop_column("execution_id")
        batch_op.drop_column("phase")
        batch_op.drop_column("effort")
        batch_op.drop_column("model")

    # ### end Alembic commands ###
