"""adiciona tentativa_falha_atual em kanban_cards

Revision ID: 96e6315ca1bf
Revises: 54e2ef2b7e2f
Create Date: 2026-08-10 11:20:28.958740
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '96e6315ca1bf'
down_revision: str | None = '54e2ef2b7e2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tentativa_falha_atual', sa.Integer(), nullable=False, server_default='0'
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanban_cards', schema=None) as batch_op:
        batch_op.drop_column('tentativa_falha_atual')

    # ### end Alembic commands ###
