"""pull_requests table

Revision ID: dc4914a546ae
Revises: 4e9c3ebf3ad9
Create Date: 2026-07-07 22:00:20.698895
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dc4914a546ae'
down_revision: str | None = '4e9c3ebf3ad9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orchestration_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('base_branch', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ci_status', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('merged_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['orchestration_id'], ['orchestrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index('ix_pulls_orch_status', ['orchestration_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_pulls_orch_status')

    op.drop_table('pull_requests')
    # ### end Alembic commands ###
