"""registro_estruturado_de_bug

Revision ID: f591aac9289f
Revises: d07dfbac77c5
Create Date: 2026-08-09 12:38:38.096618
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f591aac9289f'
down_revision: str | None = 'd07dfbac77c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_JSONB = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bug_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("orchestration_id", sa.String(), nullable=False),
        sa.Column("card_original_id", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("cenario", sa.Text(), nullable=False),
        sa.Column("passos_para_reproduzir", _JSONB, nullable=False),
        sa.Column("ambiente", sa.String(), nullable=False),
        sa.Column("resultado_atual", sa.Text(), nullable=False),
        sa.Column("resultado_esperado", sa.Text(), nullable=False),
        sa.Column("evidencias", _JSONB, nullable=False),
        sa.Column("gravidade", sa.String(), nullable=False),
        sa.Column("impacto", sa.String(), nullable=False),
        sa.Column("frequencia", sa.String(), nullable=False),
        sa.Column("agente_sugerido", sa.String(), nullable=False),
        sa.Column("retorno_de_fluxo", sa.String(), nullable=False),
        sa.Column("reportado_por", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["orchestration_id"], ["orchestrations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bug_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bug_reports_orch_card_original",
            ["orchestration_id", "card_original_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bug_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_bug_reports_orch_card_original")

    op.drop_table("bug_reports")
    # ### end Alembic commands ###
